name: Terraform CI

on:
  pull_request:
    paths:
      - "**.tf"
      - "**.tfvars"
      - ".github/workflows/terraform-ci.yml"
  push:
    branches: [main , master]

permissions:
  contents: read
  pull-requests: write

jobs:
  fmt-validate:
    name: fmt • validate • lint • scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"

      - name: terraform fmt
        run: terraform fmt -recursive -check -diff

      - name: terraform validate (all modules & live dirs)
        run: |
          set -euo pipefail
          for dir in $(find modules live bootstrap -name versions.tf -exec dirname {} \; | sort -u); do
            echo "::group::validate $dir"
            terraform -chdir="$dir" init -backend=false -input=false
            terraform -chdir="$dir" validate
            echo "::endgroup::"
          done

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: tflint
        run: |
          tflint --init
          tflint --recursive --minimum-failure-severity=warning

      - name: Trivy IaC scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: config
          scan-ref: .
          severity: HIGH,CRITICAL
          exit-code: "1"
